// Edit this list to rotate in different five-letter daily answers.
export const PAINEDLE_WORDS = [
    "aisle",
    "arbor",
    "bloom",
    "bride",
    "charm",
    "dance",
    "dream",
    "dress",
    "event",
    "faith",
    "feast",
    "flora",
    "grace",
    "groom",
    "guest",
    "honey",
    "house",
    "music",
    "party",
    "pearl",
    "photo",
    "place",
    "rings",
    "satin",
    "share",
    "smile",
    "sonic",
    "story",
    "toast",
    "union",
    "venue",
] as const;
